In [8]:
import numpy as np


### Create Numpy Array

In [9]:
arr = np.array([18,2,3,4,5,50])

In [10]:
arr

array([18,  2,  3,  4,  5, 50])

In [11]:
arr.ndim  #check dimension

1

In [15]:
arr.shape

(6,)

In [23]:
arr.reshape(2,3)

array([[18,  2,  3],
       [ 4,  5, 50]])

In [12]:
arr.dtype

dtype('int32')

In [38]:
arr.max()

50

In [39]:
arr.argmax()  # max no index

5

In [63]:
# Array with range of elements
arr = np.arange(0,11,10)
arr

<IPython.core.display.Javascript object>

array([ 0, 10])

In [19]:
# 2-D array
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
ar2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
ar2.shape

(2, 4)

In [35]:
# 3-D array
ar3 = np.array([[[1,2,3,4],[5,6,7,8]]])
ar3

<IPython.core.display.Javascript object>

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [16]:
# Higher Dimensional Array
arn = np.array([1,2,3,4,5],ndmin = 8)
arn

array([[[[[[[[1, 2, 3, 4, 5]]]]]]]])

In [18]:
arn.ndim

8

### Create Numpy Array using Numpy Function

In [54]:
# Array filled with zeros
ar_zero = np.zeros(3)
ar_zero

<IPython.core.display.Javascript object>

array([0., 0., 0.])

In [55]:
ar_zero = np.zeros((3,3))
ar_zero

<IPython.core.display.Javascript object>

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
# Array filled with ones
ar_one = np.ones(3)
ar_one

<IPython.core.display.Javascript object>

array([1., 1., 1.])

In [57]:
ar_one  = np.ones((3,2))
ar_one

<IPython.core.display.Javascript object>

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [64]:
# Array with identity matrix
ar_id = np.eye(5)
ar_id

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
ar_lin = np.linspace(0,5,10)
ar_lin

<IPython.core.display.Javascript object>

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Create Array with Random numbers

In [4]:
# rand() is used to generate a random value between 0 and 1
var = np.random.rand(2,4)
var

<IPython.core.display.Javascript object>

array([[0.09986575, 0.41134819, 0.39909319, 0.15482094],
       [0.5292248 , 0.35742633, 0.9631253 , 0.73510325]])

In [5]:
# randn() is used to generate a random value close to zero 
var = np.random.randn(5)
var

<IPython.core.display.Javascript object>

array([-1.86422406,  0.10578014, -0.08310828, -1.10117048, -0.26837951])

In [6]:
# to generate random number having  a given range
var = np.random.randint(1,100,5)
var

<IPython.core.display.Javascript object>

array([91, 28, 81, 48, 31])

In [3]:
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
var

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([3, 5, 1, 2, 4])

## Numpy operations

In [38]:
var = np.arange(0,11)

In [46]:
var

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
var + var   # use  -,*,

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
var + 5  # use -,*

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
np.add(var,var)

array([182,  56, 162,  96,  62])

In [47]:
np.sqrt(var)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [48]:
np.exp(var)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

## Numpy Indexing and Slicing

In [2]:
# one dimensional
var = np.array([9,8,7,6])
var[2]

<IPython.core.display.Javascript object>

7

In [8]:
# two dimensional
var = np.array([[9,8,7],[4,5,6]])
var[1,2]

<IPython.core.display.Javascript object>

6

In [11]:
# three dimensional
var = np.array([[[9,8],[4,5]]])
var[0,1,1]


<IPython.core.display.Javascript object>

5

In [13]:
var = np.array([1,2,3,4,5,6,7])
var[1:5]

<IPython.core.display.Javascript object>

array([2, 3, 4, 5])

In [15]:
var[1:]

array([2, 3, 4, 5, 6, 7])

In [16]:
var[:5]

array([1, 2, 3, 4, 5])

In [18]:
var[1:5:2]

array([2, 4])

In [17]:
var[::2]

array([1, 3, 5, 7])